services:
  game:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: game_container
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - spring_app_network

    environment:
      - SPRING_PROFILES_ACTIVE=docker
    env_file:
      - .env

  postgres:
    image: 'postgres:latest'
    container_name: game_db
    environment:
      - POSTGRES_DB=games
      - POSTGRES_PASSWORD=${DB_PW_PROD:-1234}
      - POSTGRES_USER=${DB_USER_PROD:-admin}
    ports:
      - '5432:5432'
    volumes:
      - gameVol:/var/lib/postgresql/data
    restart: unless-stopped

    networks:
    -  spring_app_network


  pgAdmin:
    image: 'dpage/pgadmin4'
    container_name: pg_admin
    environment:
      - PGADMIN_DEFAULT_EMAIL=mohamecabdelaziz66@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
      - '5050:80'
    depends_on:
      - postgres
    restart: unless-stopped

    networks:
      - spring_app_network

  redis:
    image: redis
    container_name: redisCont
    ports:
      - '6379:6379'
    networks:
    -  spring_app_network


volumes:
  gameVol:

networks:
  spring_app_network:
    driver: bridge




