spring:
  application:
    name: Game

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: hibernate.dialect.PostgreSQLDialect

  cache:
    type: redis

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

  servlet:
    multipart:
      enabled: true
      max-file-size: 4MB
      max-request-size: 10MB
      location: ${STORAGE_DIR}

stripe:
  api:
    secretKey: ${STRIPE_SECRET}



#stripe.success.url=localhost:8080/api/purchase/success
#stripe.cancel.url=http://localhost:8080/api/purchase/cancel
