
spring:
  datasource:
    username: ${DB_USER_PROD:admin}
    password: ${DB_PW_PROD:1234}
    url: jdbc:postgresql://postgres:5432/games

  data:
    redis:
      host: redis
      port: 6379




















































































































