spring:
  profiles:
    active: qa

  application:
    name: Game

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  cache:
    type: redis

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

  servlet:
    multipart:
      enabled: true
      max-file-size: 4MB
      max-request-size: 10MB
      location: ${STORAGE_DIR}

stripe:
  api:
    secretKey: ${STRIPE_SECRET}

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  secret_key: ${CLOUDINARY_SECRET}

