package com._Abdelaziz26.WWE.Enums;

public enum MatchType {

    SINGLES, TAG_TEAM, TRIPLE_THREAT, FATAL_4_WAY, BATTLE_ROYAL,
    HELL_IN_A_CELL, STEEL_CAGE, LADDER, TABLES, TLC, ELIMINATION_CHAMBER,
    ROYAL_RUMBLE, MONEY_IN_THE_BANK
}
